Repository UMC-DEMO-PROJECT/Chat-Sul-BE, pull requests merged in 2025-01, with the labels that each got.

#3 🚀 [chore] 프로젝트 초기 설정
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/chatsul/ChatSulApplication.java
  src/main/java/com/chatsul/apiPayload/ApiResponse.java
  src/main/java/com/chatsul/apiPayload/code/BaseCode.java
  src/main/java/com/chatsul/apiPayload/code/BaseErrorCode.java
  src/main/java/com/chatsul/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/chatsul/apiPayload/code/ReasonDTO.java
  src/main/java/com/chatsul/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/chatsul/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/chatsul/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/chatsul/apiPayload/exception/GeneralException.java
  src/main/java/com/chatsul/apiPayload/exception/handler/TempHandler.java
  src/main/java/com/chatsul/config/SwaggerConfig.java
  src/main/java/com/chatsul/converter/TempConverter.java
  src/main/java/com/chatsul/domain/Temp.java
  src/main/java/com/chatsul/domain/common/BaseEntity.java
  src/main/java/com/chatsul/domain/enums/Temp.java
  src/main/java/com/chatsul/domain/mapping/Temp.java
  src/main/java/com/chatsul/repository/TempRepository.java
  src/main/java/com/chatsul/service/TempService/TempCommandService.java
  src/main/java/com/chatsul/service/TempService/TempCommandServiceImpl.java
  src/main/java/com/chatsul/service/TempService/TempQueryService.java
  src/main/java/com/chatsul/service/TempService/TempQueryServiceImpl.java
  src/main/java/com/chatsul/web/controller/TempController.java
  src/main/java/com/chatsul/web/dto/TempRequestDTO.java
  src/main/java/com/chatsul/web/dto/TempResponseDTO.java
  src/main/resources/application.yml
  src/test/java/com/chatsul/backend/ChatSulApplicationTests.java
Labels: 🚀 chore

#7 ✨ [feat] 카카오맵 기능 구현
  src/main/java/com/chatsul/converter/VenueConverter.java
  src/main/java/com/chatsul/domain/Venue.java
  src/main/java/com/chatsul/repository/VenueRepository.java
  src/main/java/com/chatsul/service/VenueService/KakaoMapService.java
  src/main/java/com/chatsul/service/VenueService/VenueCommandService.java
  src/main/java/com/chatsul/service/VenueService/VenueCommandServiceImpl.java
  src/main/java/com/chatsul/service/VenueService/VenueQueryService.java
  src/main/java/com/chatsul/service/VenueService/VenueQueryServiceImpl.java
  src/main/java/com/chatsul/web/controller/VenueController.java
  src/main/java/com/chatsul/web/dto/VenueRequestDTO.java
  src/main/java/com/chatsul/web/dto/VenueResponseDTO.java
  src/main/resources/application.yml
Labels: ✨ feature

#14 ✨ [feat] Security 설정 및 카카오 로그인 구현
  build.gradle
  src/main/java/com/chatsul/annotation/CurrentMember.java
  src/main/java/com/chatsul/annotation/resolver/AuthenticatedMemberResolver.java
  src/main/java/com/chatsul/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/chatsul/config/PasswordConfig.java
  src/main/java/com/chatsul/config/SecurityConfig.java
  src/main/java/com/chatsul/config/WebConfig.java
  src/main/java/com/chatsul/converter/MemberConverter.java
  src/main/java/com/chatsul/converter/TokenConverter.java
  src/main/java/com/chatsul/domain/BusinessAccount.java
  src/main/java/com/chatsul/domain/Member.java
  src/main/java/com/chatsul/domain/RefreshToken.java
  src/main/java/com/chatsul/domain/enums/Bank.java
  src/main/java/com/chatsul/domain/enums/Role.java
  src/main/java/com/chatsul/jwt/filter/JwtFilter.java
  src/main/java/com/chatsul/jwt/handler/JwtAccessDeniedHandler.java
  src/main/java/com/chatsul/jwt/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/chatsul/jwt/principal/PrincipalDetails.java
  src/main/java/com/chatsul/oauth/handler/OAuthLoginFailureHandler.java
  src/main/java/com/chatsul/oauth/handler/OAuthLoginSuccessHandler.java
  src/main/java/com/chatsul/oauth/userInfo/KakaoUserInfo.java
  src/main/java/com/chatsul/oauth/userInfo/NaverUserInfo.java
  src/main/java/com/chatsul/oauth/userInfo/OAuth2UserInfo.java
  src/main/java/com/chatsul/repository/MemberRepository.java
  src/main/java/com/chatsul/repository/RefreshTokenRepository.java
  src/main/java/com/chatsul/service/AuthService/PrincipalOauth2UserService.java
  src/main/java/com/chatsul/service/AuthService/PrincipalUserDetailsService.java
  src/main/java/com/chatsul/service/MemberService/MemberCommandService.java
  src/main/java/com/chatsul/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/chatsul/service/MemberService/MemberQueryService.java
  src/main/java/com/chatsul/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/com/chatsul/service/ReservationService/ReservationCommandServiceImpl.java
  src/main/java/com/chatsul/service/TokenService/TokenService.java
  src/main/java/com/chatsul/service/TokenService/TokenServiceImpl.java
  src/main/java/com/chatsul/util/CookieUtil.java
  src/main/java/com/chatsul/util/JwtUtil.java
  src/main/java/com/chatsul/web/controller/MemberController.java
  src/main/java/com/chatsul/web/controller/TokenController.java
  src/main/java/com/chatsul/web/dto/MemberRequestDTO.java
  src/main/java/com/chatsul/web/dto/TokenResponseDTO.java
Labels: ✨ feature

#20 🐛 [fix] SecurityConfig 중복 오류 수정
  src/main/java/com/chatsul/config/security/SecurityConfig.java
Labels: 🐛 fix

#24 ✨ [feat] 매장(사업자) 생성 시 사용자 인증 추가
  src/main/java/com/chatsul/domain/Venue.java
  src/main/java/com/chatsul/service/VenueService/VenueCommandService.java
  src/main/java/com/chatsul/service/VenueService/VenueCommandServiceImpl.java
  src/main/java/com/chatsul/web/controller/VenueController.java
Labels: ✨ feature

#25 ✨ [feat] 사용자 예약 관련 사용자 인증 추가
  src/main/java/com/chatsul/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/chatsul/service/ReservationService/ReservationCommandService.java
  src/main/java/com/chatsul/service/ReservationService/ReservationCommandServiceImpl.java
  src/main/java/com/chatsul/service/ReservationService/ReservationQueryService.java
  src/main/java/com/chatsul/service/ReservationService/ReservationQueryServiceImpl.java
  src/main/java/com/chatsul/web/controller/ReservationController.java
  src/main/java/com/chatsul/web/dto/ReservationRequestDTO.java
Labels: ✨ feature

#29 ✨ [feat] 회원가입 기능 완성
  src/main/java/com/chatsul/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/chatsul/domain/BusinessAccount.java
  src/main/java/com/chatsul/domain/Member.java
  src/main/java/com/chatsul/domain/RefreshToken.java
  src/main/java/com/chatsul/oauth/handler/OAuthLoginSuccessHandler.java
  src/main/java/com/chatsul/service/MemberService/MemberCommandService.java
  src/main/java/com/chatsul/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/chatsul/service/MemberService/MemberQueryService.java
  src/main/java/com/chatsul/service/MemberService/MemberQueryServiceImpl.java
  src/main/java/com/chatsul/util/CookieUtil.java
  src/main/java/com/chatsul/util/JwtUtil.java
  src/main/java/com/chatsul/web/controller/MemberController.java
  src/main/java/com/chatsul/web/dto/MemberRequestDTO.java
Labels: ✨ feature

#33 ✨ [feat] 예약 기능 완성
  src/main/java/com/chatsul/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/chatsul/converter/ReservationConverter.java
  src/main/java/com/chatsul/domain/Member.java
  src/main/java/com/chatsul/domain/Venue.java
  src/main/java/com/chatsul/domain/enums/ReservationStatus.java
  src/main/java/com/chatsul/repository/ReservationRepository.java
  src/main/java/com/chatsul/service/ReservationService/ReservationCommandService.java
  src/main/java/com/chatsul/service/ReservationService/ReservationCommandServiceImpl.java
  src/main/java/com/chatsul/service/ReservationService/ReservationQueryService.java
  src/main/java/com/chatsul/service/ReservationService/ReservationQueryServiceImpl.java
  src/main/java/com/chatsul/service/VenueService/VenueCommandServiceImpl.java
  src/main/java/com/chatsul/web/controller/ReservationController.java
  src/main/java/com/chatsul/web/dto/ReservationResponseDTO.java
  src/main/java/com/chatsul/web/dto/VenueRequestDTO.java
Labels: ✨ feature
