Repository UMC-DEMO-PROJECT/Chat-Sul-BE, pull requests merged in 2025-02, with the labels that each got.

#31 ✨ [feat] 메뉴판 이미지 등록 및 반환 기능 구현
  build.gradle
  src/main/java/com/chatsul/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/chatsul/aws/AmazonS3Manager.java
  src/main/java/com/chatsul/config/AmazonConfig.java
  src/main/java/com/chatsul/converter/MenuConverter.java
  src/main/java/com/chatsul/converter/VenueConverter.java
  src/main/java/com/chatsul/domain/Menu.java
  src/main/java/com/chatsul/domain/Uuid.java
  src/main/java/com/chatsul/domain/Venue.java
  src/main/java/com/chatsul/repository/MenuRepository.java
  src/main/java/com/chatsul/repository/UuidRepository.java
  src/main/java/com/chatsul/service/MenuService/MenuCommandService.java
  src/main/java/com/chatsul/service/MenuService/MenuCommandServiceImpl.java
  src/main/java/com/chatsul/service/MenuService/MenuQueryService.java
  src/main/java/com/chatsul/service/MenuService/MenuQueryServiceImpl.java
  src/main/java/com/chatsul/service/VenueService/VenueCommandServiceImpl.java
  src/main/java/com/chatsul/service/VenueService/VenueQueryService.java
  src/main/java/com/chatsul/service/VenueService/VenueQueryServiceImpl.java
  src/main/java/com/chatsul/web/controller/MenuController.java
  src/main/java/com/chatsul/web/controller/VenueController.java
  src/main/java/com/chatsul/web/dto/MenuRequestDTO.java
  src/main/java/com/chatsul/web/dto/MenuResponseDTO.java
  src/main/java/com/chatsul/web/dto/VenueRequestDTO.java
  src/main/java/com/chatsul/web/dto/VenueResponseDTO.java
  src/main/resources/application.yml
Labels: ✨ feature, ♻️ refactor

#26 ✨ [feat] 분실물 기능 구현
  src/main/java/com/chatsul/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/chatsul/converter/LostItemConverter.java
  src/main/java/com/chatsul/converter/TempConverter.java
  src/main/java/com/chatsul/domain/LostItem.java
  src/main/java/com/chatsul/domain/Member.java
  src/main/java/com/chatsul/domain/Temp.java
  src/main/java/com/chatsul/domain/Venue.java
  src/main/java/com/chatsul/domain/enums/LostItemStatus.java
  src/main/java/com/chatsul/domain/enums/Temp.java
  src/main/java/com/chatsul/domain/mapping/Temp.java
  src/main/java/com/chatsul/repository/LostItemRepository.java
  src/main/java/com/chatsul/service/LostItemService/LostItemCommandService.java
  src/main/java/com/chatsul/service/LostItemService/LostItemCommandServiceImpl.java
  src/main/java/com/chatsul/service/LostItemService/LostItemQueryService.java
  src/main/java/com/chatsul/service/LostItemService/LostItemQueryServiceImpl.java
  src/main/java/com/chatsul/web/controller/LostItemController.java
  src/main/java/com/chatsul/web/controller/TempController.java
  src/main/java/com/chatsul/web/dto/LostItemRequestDTO.java
  src/main/java/com/chatsul/web/dto/LostItemResponseDTO.java
  src/main/java/com/chatsul/web/dto/TempRequestDTO.java
  src/main/java/com/chatsul/web/dto/TempResponseDTO.java
Labels: ✨ feature

#34 ✨ [feat] 소셜로그인 swagger API 명세서 추가
  src/main/java/com/chatsul/converter/MemberConverter.java
  src/main/java/com/chatsul/service/MemberService/MemberCommandService.java
  src/main/java/com/chatsul/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/chatsul/web/controller/MemberController.java
  src/main/java/com/chatsul/web/dto/MemberResponseDTO.java
Labels: ✨ feature

#36 ✨ [feat] dto 수정 및 정렬 순서 변경
  src/main/java/com/chatsul/converter/LostItemConverter.java
  src/main/java/com/chatsul/service/LostItemService/LostItemQueryServiceImpl.java
  src/main/java/com/chatsul/web/dto/LostItemResponseDTO.java
Labels: ✨ feature, ♻️ refactor

#39 ✨ [feat] 로그인 시 보유매장 정보 반환 추가
  src/main/java/com/chatsul/converter/MemberConverter.java
  src/main/java/com/chatsul/domain/Member.java
  src/main/java/com/chatsul/oauth/handler/OAuthLoginSuccessHandler.java
  src/main/java/com/chatsul/repository/MemberRepository.java
  src/main/java/com/chatsul/service/MemberService/MemberCommandServiceImpl.java
  src/main/java/com/chatsul/web/controller/MemberController.java
  src/main/java/com/chatsul/web/dto/MemberResponseDTO.java
Labels: ✨ feature

#40 ⚡ feat: 분실물 이미지 등록 기능 구현
  src/main/java/com/chatsul/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/chatsul/aws/AmazonS3Manager.java
  src/main/java/com/chatsul/config/AmazonConfig.java
  src/main/java/com/chatsul/converter/LostItemConverter.java
  src/main/java/com/chatsul/converter/VenueConverter.java
  src/main/java/com/chatsul/domain/ItemImage.java
  src/main/java/com/chatsul/domain/LostItem.java
  src/main/java/com/chatsul/repository/ItemIamgeRepository.java
  src/main/java/com/chatsul/service/LostItemService/LostItemCommandServiceImpl.java
  src/main/java/com/chatsul/service/MenuService/MenuCommandService.java
  src/main/java/com/chatsul/service/MenuService/MenuCommandServiceImpl.java
  src/main/java/com/chatsul/web/controller/LostItemController.java
  src/main/java/com/chatsul/web/controller/MenuController.java
  src/main/java/com/chatsul/web/controller/VenueController.java
  src/main/java/com/chatsul/web/dto/LostItemRequestDTO.java
  src/main/java/com/chatsul/web/dto/LostItemResponseDTO.java
  src/main/java/com/chatsul/web/dto/VenueResponseDTO.java
Labels: ✨ feature, ♻️ refactor, 📝 docs

#42 ♻️ feat: 분실물 이미지 단일 파일로 변경
  src/main/java/com/chatsul/converter/LostItemConverter.java
  src/main/java/com/chatsul/converter/MenuConverter.java
  src/main/java/com/chatsul/domain/ItemImage.java
  src/main/java/com/chatsul/domain/LostItem.java
  src/main/java/com/chatsul/domain/Menu.java
  src/main/java/com/chatsul/service/LostItemService/LostItemCommandServiceImpl.java
  src/main/java/com/chatsul/service/MenuService/MenuCommandService.java
  src/main/java/com/chatsul/service/MenuService/MenuCommandServiceImpl.java
  src/main/java/com/chatsul/web/controller/LostItemController.java
  src/main/java/com/chatsul/web/controller/MenuController.java
  src/main/java/com/chatsul/web/dto/LostItemRequestDTO.java
  src/main/java/com/chatsul/web/dto/LostItemResponseDTO.java
  src/main/java/com/chatsul/web/dto/MenuRequestDTO.java
Labels: ✨ feature, ♻️ refactor

#45 🐛 [fix] SecurityConfig 중복 오류 수정
  src/main/java/com/chatsul/config/CorsConfig.java
Labels: 🐛 fix
